---
## see https://github.com/crazy-max/ghaction-github-labeler
# Status labels
- name: "status: :scream_cat: blocked"
  color: "db1515"
  description: "Blocked (awaiting another task)"
- name: "status: :busts_in_silhouette: duplicate"
  color: "3f3f3f"
  description: "This issue or pull request already exists"
- name: "status: :zzz: on hold"
  color: "cccccc"
  description: ""
- name: "status: :pray: help wanted"
  color: "e4f404"
  description: "Extra attention is needed"
- name: "status: :no_entry_sign: invalid"
  color: "f44c04"
  description: "This doesn't seem right"
- name: "status: :thinking: needs more info"
  color: "f44c04"
  description: "Missing required information"
- name: "status: :coffin: wont do/fix"
  color: "474747"
  description: "This will not be worked on"
# Type labels
- name: "type: :sparkles: enhancement"
  color: "04f9e9"
  description: ""
- name: "type: :bulb: feature request"
  color: "04f91d"
  description: ""
- name: "type: :bug: bug"
  color: "f42004"
  description: "Something isn't working"
- name: "type: :memo: documentation"
  color: "0477f9"
  description: "Changes to documentation"
- name: "type: :construction: refactor"
  color: "04f9f9"
  description: ""
- name: "type: :ship: cicd"
  color: "f98304"
  description: "CI/CD"
- name: "type: :traffic_light: test"
  color: "f98304"
  description: ""
- name: "type: :wrench: maintenance"
  color: "fff20c"
  description: ""
- name: "type: :broom: chore"
  color: "fff20c"
  description: ""
- name: "type: :question: question"
  color: "04f919"
  description: "Further information is requested"
- name: "type: :mag: investigate"
  color: "f904b0"
  description: ""
- name: "type: :broom: linting"
  color: "775704"
  description: "Linting of code"
# Ansible labels
- name: "iac: variables"
  color: "00baaa"
  description: "Ansible Variables"
- name: "iac: tasks"
  color: "5d0d9a"
  description: "Ansible Tasks"
- name: "iac: templates"
  color: "1c15e4"
  description: "Ansible Templates"
- name: "iac: handlers"
  color: "5fd088"
  description: "Ansible Handlers"
- name: "iac: molecule"
  color: "f98304"
  description: "Molecule"
...
