---
name: 'Molecule'
on:
  workflow_dispatch:
    inputs:
      dirname:
        description: 'Name of the directory to checkout to'
        default: 'netr0m.template'
        required: false
        type: string
  workflow_call:
    inputs:
      dirname:
        description: 'Name of the directory to checkout to'
        default: 'netr0m.template'
        required: false
        type: string

env:
  PY_COLORS: 1
  ANSIBLE_FORCE_COLOR: 1

jobs:
  molecule:
    name: 'Run molecule'
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        distro:
          - debian11
          - ubuntu2204
    steps:
      - name: 'Check out the codebase'
        uses: 'actions/checkout@v2'
        with:
          path: ${{ inputs.dirname }}

      - name: 'Set up Python 3'
        uses: 'actions/setup-python@v2'
        with:
          python-version: '3.x'

      - name: 'Install dependencies'
        run: pip3 install ansible molecule[docker] docker

      - name: 'Run molecule tests'
        run: molecule test
        env:
          MOLECULE_DISTRO: ${{ matrix.distro }}
...
